NAME = human

SRC = \
Weapon.cpp \
Weapon.hpp \
HumanA.cpp \
HumanA.hpp \
 HumanB.cpp \
 HumanB.hpp \
main.cpp

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98 -g3

all:
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

run: all
	./megaphone