NAME = human

SRC = \
Weapon.cpp \
Weapon.hpp \
HumanA.cpp \
HumanA.hpp \
main.cpp
# HumanB.cpp \
# HumanB.hpp \

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

all:
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

run: all
	./megaphone